openapi: 3.0.1
info:
  title: CV API
  description: Complete CV management API with versioning support
  version: 1.0.0
  contact:
    name: API Support
    email: your-email@example.com

servers:
  - url: https://your-apim-instance.azure-api.net/cv-api/v1
    description: Production API Management Gateway

security:
  - SubscriptionKey: []

paths:
  /skills:
    get:
      tags:
        - Skills
      summary: Get all skills for the authenticated user
      operationId: GetAllSkills
      security:
        - SubscriptionKey: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      tags:
        - Skills
      summary: Create a new skill
      operationId: CreateSkill
      security:
        - SubscriptionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSkillRequest'
      responses:
        '201':
          description: Skill created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /skills/{id}:
    get:
      tags:
        - Skills
      summary: Get a specific skill by ID
      operationId: GetSkillById
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error
    put:
      tags:
        - Skills
      summary: Update an existing skill
      operationId: UpdateSkill
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSkillRequest'
      responses:
        '200':
          description: Skill updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Skills
      summary: Delete a skill
      operationId: DeleteSkill
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      responses:
        '204':
          description: Skill deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error

  /experience:
    get:
      tags:
        - Experience
      summary: Get all work experience entries
      operationId: GetAllExperience
      security:
        - SubscriptionKey: []
      parameters:
        - name: current
          in: query
          required: false
          schema:
            type: boolean
          description: Filter by current positions only
        - name: company
          in: query
          required: false
          schema:
            type: string
          description: Filter by company name
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Experience'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      tags:
        - Experience
      summary: Create a new work experience entry
      operationId: CreateExperience
      security:
        - SubscriptionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExperienceRequest'
      responses:
        '201':
          description: Experience created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /experience/{id}:
    get:
      tags:
        - Experience
      summary: Get a specific experience entry by ID
      operationId: GetExperienceById
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The experience ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
        '401':
          description: Unauthorized
        '404':
          description: Experience not found
        '500':
          description: Internal server error
    put:
      tags:
        - Experience
      summary: Update an existing experience entry
      operationId: UpdateExperience
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The experience ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExperienceRequest'
      responses:
        '200':
          description: Experience updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Experience not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Experience
      summary: Delete an experience entry
      operationId: DeleteExperience
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The experience ID
      responses:
        '204':
          description: Experience deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Experience not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    SubscriptionKey:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
      description: API subscription key for APIM

  schemas:
    Skill:
      type: object
      required:
        - id
        - name
        - level
        - category
        - ownerId
        - entityType
      properties:
        id:
          type: string
          description: Unique identifier for the skill
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill
        ownerId:
          type: string
          description: ID of the user who owns this skill
        entityType:
          type: string
          description: Type of entity (always 'skill' for skills)
          enum: ["skill"]
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the skill was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the skill was last updated

    CreateSkillRequest:
      type: object
      required:
        - name
        - level
        - category
      properties:
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill

    UpdateSkillRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

    Experience:
      type: object
      required:
        - id
        - company
        - position
        - startDate
        - employmentType
        - ownerId
        - entityType
      properties:
        id:
          type: string
          description: Unique identifier for the experience
        company:
          type: string
          description: Company name
          minLength: 1
          maxLength: 100
        position:
          type: string
          description: Job position/title
          minLength: 1
          maxLength: 100
        location:
          type: object
          properties:
            city:
              type: string
            country:
              type: string
        startDate:
          type: string
          format: date
          description: Start date of employment
        endDate:
          type: string
          format: date
          nullable: true
          description: End date of employment (null if current position)
        isCurrentPosition:
          type: boolean
          description: Whether this is the current position
          default: false
        employmentType:
          type: string
          enum: ["full-time", "part-time", "contract", "freelance"]
          description: Type of employment
        description:
          type: string
          description: Job description
          maxLength: 1000
        responsibilities:
          type: array
          items:
            type: string
          description: List of job responsibilities
        achievements:
          type: array
          items:
            type: string
          description: Key achievements in this role
        technologies:
          type: array
          items:
            type: string
          description: Technologies used in this role
        companyWebsite:
          type: string
          format: uri
          nullable: true
          description: Company website URL
        companyLogo:
          type: string
          format: uri
          nullable: true
          description: Company logo URL
        ownerId:
          type: string
          description: ID of the user who owns this experience
        entityType:
          type: string
          description: Type of entity (always 'experience')
          enum: ["experience"]
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the experience was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the experience was last updated

    CreateExperienceRequest:
      type: object
      required:
        - company
        - position
        - startDate
        - employmentType
      properties:
        company:
          type: string
          minLength: 1
          maxLength: 100
        position:
          type: string
          minLength: 1
          maxLength: 100
        location:
          type: object
          properties:
            city:
              type: string
            country:
              type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        isCurrentPosition:
          type: boolean
          default: false
        employmentType:
          type: string
          enum: ["full-time", "part-time", "contract", "freelance"]
        description:
          type: string
          maxLength: 1000
        responsibilities:
          type: array
          items:
            type: string
        achievements:
          type: array
          items:
            type: string
        technologies:
          type: array
          items:
            type: string
        companyWebsite:
          type: string
          format: uri
        companyLogo:
          type: string
          format: uri

    UpdateExperienceRequest:
      type: object
      properties:
        company:
          type: string
          minLength: 1
          maxLength: 100
        position:
          type: string
          minLength: 1
          maxLength: 100
        location:
          type: object
          properties:
            city:
              type: string
            country:
              type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        isCurrentPosition:
          type: boolean
        employmentType:
          type: string
          enum: ["full-time", "part-time", "contract", "freelance"]
        description:
          type: string
          maxLength: 1000
        responsibilities:
          type: array
          items:
            type: string
        achievements:
          type: array
          items:
            type: string
        technologies:
          type: array
          items:
            type: string
        companyWebsite:
          type: string
          format: uri
        companyLogo:
          type: string
          format: uri