openapi: 3.0.1
info:
  title: CV API
  description: Complete CV management API with versioning support
  version: 1.0.0
  contact:
    name: API Support
    email: your-email@example.com

servers:
  - url: https://your-apim-instance.azure-api.net/cv-api/v1
    description: Production API Management Gateway

security:
  - SubscriptionKey: []

paths:
  /skills:
    get:
      tags:
        - Skills
      summary: Get all skills for the authenticated user
      operationId: GetAllSkills
      security:
        - SubscriptionKey: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      tags:
        - Skills
      summary: Create a new skill
      operationId: CreateSkill
      security:
        - SubscriptionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSkillRequest'
      responses:
        '201':
          description: Skill created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /skills/{id}:
    get:
      tags:
        - Skills
      summary: Get a specific skill by ID
      operationId: GetSkillById
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error
    put:
      tags:
        - Skills
      summary: Update an existing skill
      operationId: UpdateSkill
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSkillRequest'
      responses:
        '200':
          description: Skill updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Skills
      summary: Delete a skill
      operationId: DeleteSkill
      security:
        - SubscriptionKey: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The skill ID
      responses:
        '204':
          description: Skill deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Skill not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    SubscriptionKey:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
      description: API subscription key for APIM

  schemas:
    Skill:
      type: object
      required:
        - id
        - name
        - level
        - category
        - ownerId
        - entityType
      properties:
        id:
          type: string
          description: Unique identifier for the skill
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill
        ownerId:
          type: string
          description: ID of the user who owns this skill
        entityType:
          type: string
          description: Type of entity (always 'skill' for skills)
          enum: ["skill"]
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the skill was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the skill was last updated

    CreateSkillRequest:
      type: object
      required:
        - name
        - level
        - category
      properties:
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill

    UpdateSkillRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the skill
          minLength: 1
          maxLength: 100
        level:
          type: integer
          description: Skill level (1-10)
          minimum: 1
          maximum: 10
        category:
          type: string
          description: Category of the skill
          enum: ["Programming Languages", "Frameworks & Libraries", "Databases", "Tools & Technologies", "Cloud Platforms", "Soft Skills", "Languages", "Other"]
        description:
          type: string
          description: Optional description of the skill
          maxLength: 500
        yearsOfExperience:
          type: integer
          description: Years of experience with this skill
          minimum: 0
          maximum: 50
        lastUsed:
          type: string
          format: date
          description: Date when the skill was last used
        certifications:
          type: array
          items:
            type: string
          description: List of certifications related to this skill

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details